export interface Question {
  num: number;
  stem: string;
  options: Record<string, string>;
  answer: string;
  explanation: string;
}

export const questions: Question[] = [
  {
    num: 71,
    stem: "A 58-year-old woman with sickle cell anaemia who has received multiple red cell transfusions presents with jaundice and dark urine 7 days after a routine transfusion for acute chest syndrome. Laboratory studies: haemoglobin 58 g/L (was 78 g/L post-transfusion), total bilirubin 92 µmol/L, lactate dehydrogenase 820 U/L, haptoglobin <0.1 g/L. The direct antiglobulin test is positive for IgG. The pre-transfusion antibody screen was negative. Which of the following best explains the underlying mechanism and the most appropriate immediate investigation?",
    options: {
      A: "Immediate ABO-incompatible transfusion due to clerical error; stop all transfusions and switch to group O Rh D-negative blood permanently.",
      B: "Delayed haemolytic transfusion reaction from an anamnestic response to a previously undetectable Rh alloantibody; repeat the antibody screen and cross-match using enzyme-treated cells and an extended antigen panel.",
      C: "Hyperhaemolysis syndrome from macrophage overactivity; treat with high-dose corticosteroids and eculizumab, and avoid all future transfusions.",
      D: "Autoimmune haemolytic anaemia triggered by the stress of acute chest syndrome; start prednisolone 1 mg/kg/day and perform splenectomy if refractory.",
      E: "Bacterial contamination of the red cell unit with Yersinia enterocolitica; start broad-spectrum intravenous antibiotics and obtain blood cultures from the donor unit."
    },
    answer: "B",
    explanation: "Hoffbrand describes delayed haemolytic transfusion reactions as occurring when a patient has been previously immunized to a red cell antigen (most commonly of the Rh system, e.g. anti-c, anti-E) but the pre-transfusion antibody level is below the detection threshold of the routine cross-match. Re-exposure to the antigen by transfusion triggers an anamnestic immune response, coating the transfused red cells with IgG and causing accelerated extravascular clearance in the reticuloendothelial system days after transfusion. This presents with falling haemoglobin, jaundice, a positive direct antiglobulin test and sometimes mild haemoglobinuria. Investigation requires re-testing the patient's serum against an extended panel of phenotyped red cells using sensitive methods such as enzyme-treated cells or polyethylene glycol to identify the responsible alloantibody, and selecting antigen-negative blood for future transfusions. Immediate ABO reactions occur within minutes to hours and are complement-mediated, causing intravascular haemolysis with IgM and C3d positivity. Hyperhaemolysis syndrome is a distinct entity in sickle cell disease characterized by destruction of both donor and recipient red cells without detectable alloantibodies, and while steroids and eculizumab are used, it is not the most likely explanation here given the isolated destruction of donor cells and IgG-positive DAT. Autoimmune haemolytic anaemia is not the most parsimonious diagnosis in this context of recent transfusion with a previously negative screen. Bacterial contamination presents with acute septic shock and fever within hours, not delayed jaundice."
  },
  {
    num: 72,
    stem: "A 45-year-old man with acute-on-chronic liver failure receives 2 units of fresh frozen plasma prior to emergency endoscopy for variceal bleeding. Within 2 hours he develops acute dyspnoea, fever 38.9°C and rigors. Chest X-ray shows diffuse bilateral airspace infiltrates. His blood pressure is stable, there is no jugular venous distension, and brain natriuretic peptide is not elevated. Which of the following best describes the diagnosis and its pathophysiological mechanism?",
    options: {
      A: "Transfusion-associated circulatory overload (TACO); the management is intravenous furosemide and slower transfusion rates in future.",
      B: "Transfusion-related acute lung injury (TRALI) caused by donor leucoagglutinins (HLA antibodies) in plasma, usually from a multiparous female donor; management requires high-dependency or intensive care unit support with ventilator assistance if needed.",
      C: "Anaphylactic reaction due to IgA deficiency in the recipient; immediate intramuscular epinephrine is required, followed by corticosteroids.",
      D: "Bacterial contamination of the FFP unit with Pseudomonas aeruginosa; present with septic shock and manage with broad-spectrum antibiotics and blood cultures.",
      E: "Febrile non-haemolytic transfusion reaction from cytokines in residual donor leucocytes; treat with paracetamol and antihistamines and continue transfusion."
    },
    answer: "B",
    explanation: "Hoffbrand describes transfusion-related acute lung injury (TRALI) as presenting within 6 hours of transfusion with cough, breathlessness, fever and rigors, with pulmonary infiltrates visible on chest X-ray. It is caused by transfer of leucoagglutinins (HLA antibodies) in donor plasma or platelets, which cause endothelial and epithelial injury in the pulmonary vasculature. Most implicated donors are multiparous women who have been alloimmunized through pregnancy. Consequently, in the United Kingdom and United States, FFP and plasma used to support platelet pools are now sourced preferentially from male donors to reduce TRALI risk. Management is in a high-dependency or intensive care unit with ventilator support if needed. TACO presents with signs of left ventricular failure, elevated BNP and jugular venous distension, which are absent here. Anaphylaxis in IgA-deficient subjects is characterized by shock, bronchospasm, laryngeal oedema and widespread angioedema, not isolated pulmonary infiltrates. Bacterial contamination of FFP is very rare and would typically present with acute circulatory collapse and endotoxin shock rather than isolated lung injury. Febrile non-haemolytic reactions can cause pyrexia and rigors but do not produce diffuse bilateral pulmonary infiltrates or severe hypoxia."
  },
  {
    num: 73,
    stem: "A 24-year-old man is brought to the emergency department after a high-speed road traffic accident. He has lost approximately 40% of his blood volume and is hypotensive. He receives 8 units of group O Rh D-negative red cells, 4 units of fresh frozen plasma and 1 pool of platelets over 3 hours. During the resuscitation he develops tetany, a prolonged QT interval on ECG, and hypotension refractory to volume replacement. Arterial blood gas shows ionized calcium 0.72 mmol/L (normal 1.15–1.30). Which of the following best explains this complication and the most appropriate immediate management?",
    options: {
      A: "Acute intravascular haemolysis from an ABO-incompatible transfusion; immediately stop the transfusion and send a direct antiglobulin test and compatibility check.",
      B: "Hyperkalaemia from the potassium load of stored red cells causing ventricular arrhythmia; administer calcium gluconate, insulin-glucose and salbutamol nebulisers.",
      C: "Citrate toxicity from the anticoagulant in large-volume red cell and FFP transfusion, binding ionized calcium; administer intravenous calcium replacement and slow the transfusion rate if possible.",
      D: "Dilutional coagulopathy from massive transfusion causing disseminated intravascular coagulation; start therapeutic unfractionated heparin.",
      E: "Air embolism introduced through the central venous catheter; place the patient in the left lateral decubitus position and attempt aspiration of air from the right ventricle."
    },
    answer: "C",
    explanation: "Hoffbrand lists citrate toxicity as a recognized complication of massive transfusion. The citrate anticoagulant in stored blood components (red cells, FFP, platelets) combines with ionized calcium. During massive or rapid transfusion, the recipient's liver may be unable to metabolise the citrate load quickly enough, leading to symptomatic hypocalcaemia manifesting as tetany, prolonged QT interval, and hypotension refractory to volume resuscitation. Intravenous calcium replacement (e.g. calcium chloride or calcium gluconate) is the immediate corrective therapy, and slowing the transfusion rate reduces further citrate load. Hyperkalaemia is another potential complication of massive transfusion, especially with older red cells, but would not typically present with tetany and a documented low ionized calcium; the blood gas result points directly to hypocalcaemia. Acute intravascular haemolysis from ABO incompatibility occurs within minutes to hours of starting the transfusion and is characterized by immediate shock, haemoglobinuria and complement-mediated intravascular haemolysis, not tetany. Dilutional coagulopathy may occur in massive transfusion but would present with prolonged PT/APTT and low fibrinogen, not hypocalcaemia. Air embolism is rare and presents with acute cardiovascular collapse and a millwheel murmur, not tetany or QT prolongation."
  },
  {
    num: 74,
    stem: "A 62-year-old woman undergoes elective total hip replacement and receives 2 units of leucodepleted red cells intraoperatively for a postoperative haemoglobin of 78 g/L. She is discharged on day 3. Ten days later she returns with widespread petechiae, ecchymoses and epistaxis. Laboratory studies: platelet count 4 × 10⁹/L (was 220 × 10⁹/L preoperatively), haemoglobin 105 g/L, white cell count 8.2 × 10⁹/L. She is afebrile and blood cultures are negative. Which of the following best describes the most likely diagnosis and optimal management?",
    options: {
      A: "Heparin-induced thrombocytopenia from postoperative low molecular weight heparin prophylaxis; discontinue all heparin and initiate a direct thrombin inhibitor or fondaparinux.",
      B: "Post-transfusion purpura caused by an anti-platelet-specific antigen antibody (typically anti-HPA-1a) that destroys both transfused and autologous platelets; treat with intravenous immunoglobulin or plasma exchange if severe.",
      C: "Disseminated intravascular coagulation from surgical trauma and immobilization; administer fresh frozen plasma, cryoprecipitate and platelets.",
      D: "Transfusion-associated graft-versus-host disease from viable donor lymphocytes in the leucodepleted unit; start high-dose corticosteroids and ensure all future cellular products are irradiated.",
      E: "Immune thrombocytopenia triggered by surgical stress and anaesthetic agents; administer high-dose corticosteroids and platelet transfusion."
    },
    answer: "B",
    explanation: "Hoffbrand describes post-transfusion purpura as a rare but serious complication characterized by severe thrombocytopenia occurring 7–10 days after transfusion of a platelet-containing product, most commonly red cells. It is caused by an antibody in the recipient (usually resulting from prior transfusion or pregnancy) directed against a platelet-specific antigen, most often HPA-1a (PlA1). The immune complexes destroy both the transfused and the recipient's own platelets, leading to profound thrombocytopenia. It is usually self-limiting, but intravenous immunoglobulin or plasma exchange may be needed in severe cases. The timing (day 10), the severity of thrombocytopenia in isolation, and the recent transfusion history are highly characteristic. Heparin-induced thrombocytopenia typically occurs 5–10 days after heparin exposure and is associated with thrombosis; while it is a differential, the recent red cell transfusion makes post-transfusion purpura more specific. DIC would present with coagulopathy (prolonged PT/APTT, low fibrinogen, elevated D-dimer) and is not confined to isolated thrombocytopenia. GVHD presents with fever, rash, diarrhoea, liver dysfunction and pancytopenia, not isolated thrombocytopenia at day 10. Leucodepletion reduces but does not eliminate the risk of GVHD, and irradiation is the definitive preventive measure, but GVHD is not the diagnosis here. Surgical stress does not cause severe immune thrombocytopenia."
  },
  {
    num: 75,
    stem: "A 34-year-old man with B-cell prolymphocytic leukaemia is started on fludarabine 25 mg/m² daily for 5 days. He has a haemoglobin of 72 g/L and requires red cell transfusion support during chemotherapy. He has no history of transfusion reactions and is CMV seropositive. Which of the following is the most important modification to standard transfusion practice for this patient?",
    options: {
      A: "Use CMV-negative blood products exclusively because fludarabine-induced T-cell suppression predisposes to primary CMV infection.",
      B: "Irradiate all cellular blood products to prevent transfusion-associated graft-versus-host disease, because fludarabine is a purine antagonist that causes profound and prolonged T-cell immunosuppression.",
      C: "Use washed red cells to prevent anaphylaxis from donor plasma proteins, as fludarabine increases the risk of IgA antibody formation.",
      D: "Administer granulocyte concentrates concurrently with red cells to treat both the anaemia and anticipated neutropenia.",
      E: "Use fresh frozen plasma instead of red cells to avoid transfusional iron overload, because fludarabine accelerates hepatic iron deposition."
    },
    answer: "B",
    explanation: "Hoffbrand explicitly lists patients treated with fludarabine—and other purine antagonists such as bendamustine, cladribine and pentostatin—as requiring irradiated blood products. Transfusion-associated graft-versus-host disease (TA-GVHD) is a potentially fatal complication that occurs when viable donor lymphocytes in cellular blood products engraft and attack the immunocompromised recipient's tissues. Fludarabine causes profound and prolonged T-cell immunosuppression, rendering patients highly susceptible to TA-GVHD. The chapter specifies irradiation as the mandatory preventive measure for this group. CMV-negative blood is indicated for CMV-negative immunosuppressed recipients (e.g. allogeneic stem cell transplant recipients, premature infants), but since this patient is already CMV seropositive, CMV-negative blood is not the most critical modification. Washed red cells are reserved for patients with severe allergic reactions or IgA deficiency, not for fludarabine recipients. Granulocyte concentrates are used only for severe neutropenia with life-threatening infection unresponsive to antibiotics and are not indicated for anaemia. FFP cannot substitute for red cells in treating symptomatic anaemia because it does not carry oxygen; moreover, fludarabine does not accelerate iron overload."
  },
  {
    num: 76,
    stem: "Regarding the molecular genetics and biochemistry of the ABO blood group system, which of the following statements is most accurate?",
    options: {
      A: "The A and B alleles encode the same glycosyltransferase but with different post-translational glycosylation patterns; the O allele is a silent allele that produces a truncated yet enzymatically active protein.",
      B: "The A and B alleles each encode distinct glycosyltransferases that add N-acetylgalactosamine or galactose, respectively, to the H substance; the O allele is non-functional and leaves the H substance unmodified.",
      C: "The H substance is absent in all individuals with the Bombay phenotype (hh), but anti-H antibodies are clinically significant in routine blood grouping of the general population and cause widespread transfusion incompatibility.",
      D: "The A1 and A2 subtypes differ because the A2 allele has a frameshift mutation that abolishes glycosyltransferase activity; A2B patients are routinely misgrouped as group O because of undetectable antigen expression.",
      E: "The ABO antigens are expressed exclusively on erythrocyte membranes and are never found on white cells, platelets or in body secretions such as saliva and plasma."
    },
    answer: "B",
    explanation: "Hoffbrand states that the protein defining the ABO antigens is a glycosyltransferase encoded from a single gene for which there are three major alleles: A, B and O. The A and B alleles catalyse the addition of different carbohydrate residues—N-acetylgalactosamine for group A and galactose for group B—to a basic antigenic glycoprotein or glycolipid with a terminal L-fucose on the red cell, known as the H substance (Hoffbrand Fig. 33.2). The O allele is non-functional and therefore does not modify the H substance. This is the central molecular basis of ABO blood group inheritance and antigen expression. Option A is incorrect because the A and B alleles encode functionally distinct transferases with different substrate specificities, and the O allele is completely non-functional, not truncated and active. Option C is incorrect because while the Bombay phenotype (hh) lacks H substance, anti-H antibodies do not interfere with routine blood grouping in the general population since H is universally present on non-Bombay red cells. Option D is incorrect because A2 cells react more weakly than A1 cells with anti-A, but the A2 allele is not a frameshift mutation; A2B patients may be wrongly grouped as B (not O) because of weak A2 antigen expression. Option E is incorrect because A, B and H antigens are present on most body cells including white cells and platelets, and in soluble form in the secretions and body fluids of the 80% of the population who possess secretor genes."
  },
  {
    num: 77,
    stem: "Regarding the antiglobulin (Coombs') test in blood group serology and clinical immunohaematology, which of the following best describes the fundamental principle and correct clinical application?",
    options: {
      A: "The direct antiglobulin test (DAT) detects antibodies coating red cells in vitro by incubating patient serum with donor red cells; a positive DAT indicates the presence of alloantibodies in the patient's plasma.",
      B: "The indirect antiglobulin test (IAT) is a one-stage procedure in which antihuman globulin is added directly to the patient's red cells to detect antibodies already bound in vivo; it is the diagnostic test of choice for autoimmune haemolytic anaemia.",
      C: "Antihuman globulin (AHG) reagent is produced by immunizing animals with human immunoglobulin or complement components; when added to sensitized red cells, agglutination indicates a positive test, with the DAT used for in vivo sensitization and the IAT for in vitro detection of antibodies.",
      D: "The IAT is performed at 4°C to detect cold-reacting IgM antibodies such as anti-A and anti-B; it is the routine method for ABO compatibility testing in automated analysers.",
      E: "Saline agglutination at 37°C is used to detect clinically significant IgG immune antibodies; the IAT has been entirely replaced by gel-based microcolumn technology and is no longer required for compatibility testing."
    },
    answer: "C",
    explanation: "Hoffbrand describes the antiglobulin (Coombs') test as a fundamental technique in both blood group serology and general immunology. Antihuman globulin (AHG) is produced in animals following injection of human globulin, purified complement or specific immunoglobulins (e.g. IgG, IgA, IgM), and monoclonal preparations are now also available. When AHG is added to human red cells coated with immunoglobulin or complement components, agglutination indicates a positive test (Hoffbrand Fig. 33.5). The direct antiglobulin test (DAT) is used for detecting antibody or complement already on the red cell surface where sensitization has occurred in vivo; it is positive in haemolytic disease of the newborn, autoimmune or drug-induced immune haemolytic anaemia, and haemolytic transfusion reactions. The indirect antiglobulin test (IAT) is a two-stage procedure used to detect antibodies that have coated red cells in vitro; the first stage incubates test red cells with serum, and the second stage adds AHG after washing. The IAT is used for routine antibody screening of the recipient's serum prior to transfusion and for detecting blood group antibodies in pregnant women. Option A incorrectly describes the DAT as an in vitro test for alloantibodies in plasma. Option B incorrectly describes the IAT as a one-stage test for in vivo sensitization. Option D is incorrect because the IAT is performed at 37°C for clinically significant warm IgG antibodies, not at 4°C for cold IgM antibodies. Option E is incorrect because saline agglutination at 37°C detects IgM antibodies, and while gel-based technology is now widely used, the IAT principle remains central to compatibility testing."
  },
  {
    num: 78,
    stem: "Regarding the evidence-based thresholds for platelet transfusion support, which of the following statements most accurately reflects current practice as described in Hoffbrand?",
    options: {
      A: "Prophylactic platelet transfusion is universally indicated to maintain the count above 50 × 10⁹/L in all hospitalized patients, regardless of whether they are bleeding or undergoing invasive procedures.",
      B: "For insertion of a central venous catheter, the platelet count should exceed 20 × 10⁹/L; for lumbar puncture it should exceed 40 × 10⁹/L; and for brain or eye surgery other than cataract removal, it should exceed 100 × 10⁹/L.",
      C: "Platelet transfusions are first-line therapy for immune thrombocytopenic purpura (ITP) in non-bleeding patients because they reliably raise the count and reduce the risk of spontaneous intracranial haemorrhage.",
      D: "In thrombotic thrombocytopenic purpura (TTP), prophylactic platelet transfusions are recommended when the count falls below 10 × 10⁹/L to prevent catastrophic bleeding.",
      E: "Refractoriness to platelet transfusion is defined by a post-transfusion increment of less than 10 × 10⁹/L at 1 hour; HLA alloimmunization is the only cause and can be overcome simply by increasing the dose of random-donor platelets."
    },
    answer: "B",
    explanation: "Hoffbrand provides specific platelet count thresholds for various clinical scenarios. For prophylaxis, the count should be kept above 10 × 10⁹/L unless there are additional risk factors such as sepsis, drug use or coagulation disorders, in which case the threshold should be above 20 × 10⁹/L. For insertion of a venous catheter the count should be >20 × 10⁹/L, for lumbar puncture >40 × 10⁹/L, for invasive procedures or major surgery >50 × 10⁹/L, for insertion or removal of epidural catheters >80 × 10⁹/L, and for brain or eye surgery other than cataract removal >100 × 10⁹/L. Option A is incorrect because a universal threshold of 50 × 10⁹/L is not applied to all hospitalized patients; the routine prophylactic threshold is 10 × 10⁹/L. Option C is incorrect because platelet transfusions are avoided in autoimmune thrombocytopenic purpura unless there is serious haemorrhage, as the transfused platelets are rapidly destroyed by autoantibodies. Option D is incorrect because platelet transfusions are contraindicated in thrombotic thrombocytopenic purpura and haemolytic uraemic syndrome as they may exacerbate thrombosis. Option E is incorrect because refractoriness is defined by a poor increment (less than 7.5 × 10⁹/L per unit at 1 hour or less than 4.5 × 10⁹/L at 24 hours) and causes include both immunological factors (mostly HLA alloimmunization) and non-immunological factors (sepsis, hypersplenism, DIC, drugs); HLA-matched or cross-match-compatible platelets are needed for patients with HLA antibodies, not simply a higher dose of random-donor platelets."
  },
  {
    num: 79,
    stem: "Which of the following most accurately describes the rationale, definition and clinical benefits of universal leucodepletion of cellular blood components?",
    options: {
      A: "Leucodepletion is defined as removal of white cells to <1 × 10⁶ per unit; its primary purpose is to prevent bacterial contamination during red cell storage at 4°C.",
      B: "Leucodepletion reduces the incidence of febrile transfusion reactions and HLA alloimmunization, prevents CMV transmission, and reduces the theoretical risk of nvCJD prion transmission; a component is defined as leucocyte-depleted if white cells are <5 × 10⁶ per unit.",
      C: "Leucodepletion is performed exclusively at the bedside immediately prior to transfusion because bedside filtration is more effective than filtration at the time of collection.",
      D: "The primary indication for leucodepletion is elimination of donor lymphocytes to prevent transfusion-associated GVHD; irradiation of blood products is unnecessary if leucodepleted blood is used.",
      E: "Leucodepletion is mandatory only for patients with a known history of febrile transfusion reactions; routine universal leucodepletion offers no benefit to first-time transfusion recipients."
    },
    answer: "B",
    explanation: "Hoffbrand states that in many countries, including the United Kingdom and United States, blood products are now routinely filtered to remove the majority of white cells, a process known as leucodepletion. This is usually performed soon after collection and prior to processing, and is more effective than filtration of blood at the bedside. A blood component is defined as leucocyte-depleted if there are less than 5 × 10⁶ white cells present per unit. The benefits include reduction in the incidence of febrile transfusion reactions and HLA alloimmunization, prevention of CMV transmission, and reduction of the theoretical possibility of transmission of new variant Creutzfeldt–Jacob disease (nvCJD) in countries where this has been reported. Option A is incorrect because the threshold is <5 × 10⁶ per unit, not <1 × 10⁶, and the primary purpose is not bacterial contamination prevention. Option C is incorrect because collection-time or processing-time filtration is more effective than bedside filtration. Option D is incorrect because while leucodepletion substantially reduces the white cell load, it does not eliminate the risk of GVHD; irradiation remains required for susceptible recipients such as stem cell transplant recipients and patients treated with purine antagonists. Option E is incorrect because universal leucodepletion benefits all recipients, including first-time transfusion recipients, by reducing CMV transmission risk, febrile reactions and HLA sensitization."
  },
  {
    num: 80,
    stem: "Regarding the screening and epidemiology of transfusion-transmitted infections, which of the following statements most accurately reflects current UK and US practice as described in Hoffbrand?",
    options: {
      A: "All blood donations in the UK are screened for prions using a validated nucleic acid amplification test; donors who lived in the UK for at least 3 months between 1980 and 1996 are permanently barred from donation in the United States.",
      B: "In the United States, blood is screened for eight microbial pathogen types including bacterial contamination, HBV, HCV, HIV-1/2, HTLV-I/II, syphilis and West Nile virus; universal Zika virus nucleic acid testing was added in 2018.",
      C: "Hepatitis E virus (HEV) RNA testing is performed on every individual blood donation in the UK using single-donation nucleic acid testing because HEV is the most common transfusion-transmitted virus globally.",
      D: "In non-endemic areas, all donors are routinely tested for malaria antibodies and all recipients of cellular blood products receive mandatory antimalarial chemoprophylaxis.",
      E: "Cytomegalovirus (CMV) antibody testing is performed on all donations in the UK, and CMV-positive blood is discarded; only CMV-negative blood is issued to any recipient regardless of immune status."
    },
    answer: "B",
    explanation: "Hoffbrand states that in the United States, blood products are tested for eight microbial pathogen types: bacterial contamination (blood culture), hepatitis B (core antibody and surface antigen), hepatitis C (antibody and nucleic acid amplification testing), HIV-1 and HIV-2 (antibody testing for both, and nucleic acid testing for HIV-1), HTLV-I and HTLV-II (antibody testing for both), Treponema pallidum (anti-treponemal antibody testing) and West Nile virus (nucleic acid testing). In 2018, universal testing for Zika virus (a nucleic acid test) was added. Option A is incorrect because no reliable screening test for prions exists; the US permanently bars donors who lived in the UK for at least 3 months between 1980 and 1996 due to perceived nvCJD risk, but the UK does not screen for prions. Option C is incorrect because HEV RNA testing in the UK is performed on pools of 24 donations, not single donations, and hepatitis B remains the most important transfusion-transmitted virus because it is readily transmitted and has a window period. Option D is incorrect because in non-endemic areas donors are carefully vetted for tropical travel and some centres test for malarial antibodies, but mandatory antimalarial chemoprophylaxis for all recipients is not standard practice. Option E is incorrect because CMV antibody testing is performed for immunosuppressed recipients, not all donations, and CMV-positive blood is not discarded; it is used for CMV-positive recipients or when CMV-negative blood is unavailable."
  }
];
